server {
  listen 80;
  server_name _;
  client_max_body_size 50m;
  error_page 500 502 503 504 /friendly-50x.html;

  location = /friendly-50x.html {
    internal;
    root /usr/share/nginx/html;
  }

  location /api/ {
    proxy_intercept_errors off;
    proxy_pass http://api:6272/api/;
    proxy_http_version 1.1;
    proxy_set_header Host $http_host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
  }

  location /signin-google {
    proxy_intercept_errors off;
    proxy_pass http://api:6272/signin-google;
    proxy_http_version 1.1;
    proxy_set_header Host $http_host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
  }

  location /static/images/ {
    alias /var/www/incos-static/images/;
    autoindex off;
    try_files $uri =404;
    add_header Cache-Control "public, max-age=31536000, immutable";
  }

  location / {
    proxy_intercept_errors on;
    proxy_pass http://frontend:6173;
    proxy_http_version 1.1;
    proxy_set_header Host $http_host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
  }
}
