import type { WorkspaceModeConfig } from './types';

const sharedFilterSection = {
  id: 'quick-filters',
  label: 'Filters',
  items: [
    { id: 'priority', label: 'Priority', icon: 'star' },
    { id: 'has-link', label: 'Has Link', icon: 'link' },
    { id: 'checklist', label: 'Checklist', icon: 'list-checks' },
  ],
};

export const defaultModeConfigs: WorkspaceModeConfig[] = [
  {
    id: 'academy',
    displayName: 'Academy',
    icon: 'graduation-cap',
    enabled: true,
    purpose:
      'Manage school, study, courses, lectures, assignments, quizzes, exams, routines, and notes.',
    accent: { primary: '#b87503', secondary: '#4f6f46' },
    features: ['calendar', 'agenda', 'board', 'timeline', 'checklist', 'routines', 'notes', 'links', 'integrations'],
    views: ['month', 'agenda', 'board', 'timeline'],
    sidebar: [
      {
        id: 'menu',
        label: 'Menu',
        items: [
          { id: 'dashboard', label: 'Dashboard', icon: 'layout-dashboard' },
          { id: 'courses', label: 'Courses', icon: 'book-open' },
          { id: 'grades', label: 'Grades', icon: 'bar-chart-3' },
          { id: 'inbox', label: 'Inbox', icon: 'inbox', feature: 'integrations' },
          { id: 'people', label: 'People', icon: 'users' },
          { id: 'outlook', label: 'Outlook', icon: 'outlook', feature: 'integrations' },
          { id: 'settings', label: 'Settings', icon: 'settings' },
        ],
      },
    ],
    dashboardCards: [
      {
        id: 'semester-lectures',
        title: 'Courses',
        pill: 'Summer 2026',
        color: 'green',
        layout: 'agenda',
        maxRows: 5,
        rows: [
          { id: 'cs101', label: 'CS101', value: 'Computer Science lecture' },
          { id: 'math202', label: 'MATH202', value: 'Mathematics lecture' },
          { id: 'eng110', label: 'ENG110', value: 'Academic writing lecture' },
        ],
      },
      {
        id: 'upcoming-coursework',
        title: 'Coursework',
        color: 'blue',
        layout: 'agenda',
        rows: [
          { id: 'assignment-a', label: 'CMPT225', value: 'Assignment 1', description: 'May 27, 11:59 PM' },
          { id: 'eng-discussion', label: 'ENGL110', value: 'Discussion post', description: 'May 28, 5:00 PM' },
          { id: 'math-activity', label: 'MATH202', value: 'Activity set', description: 'May 29, 10:00 AM' },
        ],
      },
    ],
    filters: [
      {
        id: 'courses',
        label: 'Courses',
        options: [
          { id: 'cs101', label: 'CS101', color: 'blue', defaultChecked: true },
          { id: 'math202', label: 'MATH202', color: 'orange', defaultChecked: true },
          { id: 'eng110', label: 'ENG110', color: 'purple', defaultChecked: true },
        ],
      },
      {
        id: 'routine',
        label: 'Routine',
        options: [
          { id: 'morning', label: 'Morning', color: 'green', defaultChecked: true },
          { id: 'study', label: 'Study', color: 'teal', defaultChecked: true },
          { id: 'sleep', label: 'Sleep', color: 'gray' },
        ],
      },
    ],
    calendar: {
      title: 'Academy Calendar',
      subtitle: '',
      behavior: [
        'Mood and routine status can appear in each day cell.',
        'Assignment starts use a light dot, active assignment spans use thin timeline bars, and due dates use stronger markers.',
        'Quizzes, exams, lectures, office hours, and meeting links remain distinct calendar item types.',
      ],
      itemTypes: [
        { id: 'lecture', label: 'Lecture', color: 'green', marker: 'meeting' },
        { id: 'assignment-start', label: 'Assignment start', color: 'blue', marker: 'dot' },
        { id: 'assignment-period', label: 'Assignment period', color: 'blue', marker: 'line' },
        { id: 'due-date', label: 'Due date', color: 'red', marker: 'due' },
        { id: 'quiz-exam', label: 'Quiz or exam', color: 'orange', marker: 'milestone' },
        { id: 'office-hour', label: 'Office hour', color: 'teal', marker: 'meeting' },
      ],
    },
    board: {
      columns: [
        { id: 'cmpt225', label: 'CMPT225', color: 'blue' },
        { id: 'math202', label: 'MATH202', color: 'orange' },
        { id: 'engl110', label: 'ENGL110', color: 'purple' },
        { id: 'cmpt276', label: 'CMPT276', color: 'green' },
      ],
    },
    detailFields: [
      { id: 'type', label: 'Type' },
      { id: 'course', label: 'Course' },
      { id: 'start', label: 'Start' },
      { id: 'due', label: 'Due' },
    ],
    addItemFields: [
      {
        id: 'type',
        label: 'Type',
        type: 'select',
        options: ['Assignment', 'Lecture', 'Quiz', 'Exam', 'Routine', 'Study Session'],
        required: true,
      },
      { id: 'title', label: 'Title', type: 'text', fullWidth: true, required: true },
      { id: 'course', label: 'Course', type: 'text' },
      { id: 'startDate', label: 'Start Date', type: 'date' },
      { id: 'dueDate', label: 'Due Date', type: 'date' },
      {
        id: 'priority',
        label: 'Priority',
        type: 'priority',
        options: ['High', 'Medium', 'Low'],
      },
      { id: 'meetingLink', label: 'Meeting or Notes Link', type: 'url', fullWidth: true },
      {
        id: 'notes',
        label: 'Checklist and Notes',
        type: 'textarea',
        fullWidth: true,
        placeholder: 'Add study checklist items, notes, or portal reminders...',
      },
    ],
    timeline: {
      label: 'Study timeline',
      behavior: 'Assignments and exam prep can render as thin calendar spans or timeline tracks.',
    },
    integrations: [
      { provider: 'canvas_lms', enabled: true, label: 'Canvas LMS' },
      { provider: 'google_calendar', enabled: false, label: 'Google Calendar' },
      { provider: 'google_meet', enabled: false, label: 'Google Meet' },
      { provider: 'google_drive', enabled: false, label: 'Google Drive' },
      { provider: 'gmail', enabled: false, label: 'Gmail' },
      { provider: 'microsoft_outlook', enabled: true, label: 'Outlook' },
    ],
  },
  {
    id: 'project',
    displayName: 'Workspace',
    icon: 'rocket',
    enabled: true,
    purpose:
      'Manage general customer workload, projects, issues, shared schedules, follow-ups, and timelines.',
    accent: { primary: '#8a5a00', secondary: '#0f766e' },
    features: ['calendar', 'agenda', 'board', 'timeline', 'issues', 'customers', 'checklist', 'links', 'integrations'],
    views: ['month', 'agenda', 'board', 'timeline'],
    sidebar: [
      {
        id: 'menu',
        label: 'Menu',
        items: [
          { id: 'dashboard', label: 'Dashboard', icon: 'layout-dashboard' },
          { id: 'project', label: 'Projects', icon: 'clipboard-list' },
          { id: 'calendar', label: 'Calendar', icon: 'calendar-days', feature: 'calendar' },
          { id: 'board', label: 'To Do', icon: 'columns-3', feature: 'board' },
          { id: 'timeline', label: 'Timeline', icon: 'gantt-chart', feature: 'timeline' },
          { id: 'issues', label: 'Issues', icon: 'circle-alert', feature: 'issues' },
          { id: 'bugs', label: 'Work Items', icon: 'list-checks' },
          { id: 'features', label: 'Customer Requests', icon: 'message-square' },
          { id: 'customers', label: 'Customers', icon: 'message-square', feature: 'customers' },
          { id: 'colleagues', label: 'Colleagues', icon: 'users' },
          { id: 'categories', label: 'Categories', icon: 'tags' },
          { id: 'email', label: 'Email', icon: 'gmail', feature: 'integrations' },
          { id: 'chat', label: 'Chat', icon: 'google-chat', feature: 'integrations' },
          { id: 'drive', label: 'Drive', icon: 'google-drive', feature: 'integrations' },
          { id: 'toptrack', label: 'TopTrack', icon: 'toptrack', feature: 'integrations' },
          { id: 'links', label: 'Links', icon: 'link', feature: 'links' },
          { id: 'settings', label: 'Settings', icon: 'settings' },
        ],
      },
      sharedFilterSection,
    ],
    dashboardCards: [
      {
        id: 'agenda',
        kicker: 'Agenda',
        title: '4 items today',
        color: 'blue',
        layout: 'agenda',
        rows: [
          { label: '10:00', value: 'Customer project review' },
          { label: '13:30', value: 'TopSolid CAM follow-up' },
          { label: '17:00', value: 'Eureka delivery planning' },
        ],
      },
      {
        id: 'messages',
        kicker: 'Messages',
        title: '8 unread',
        color: 'orange',
        layout: 'messages',
        rows: [
          {
            label: 'now',
            value: 'Customer replied',
            description: 'ABC Client sent a login issue update from Gmail...',
            source: 'gmail',
          },
          {
            label: '2m',
            value: 'Project channel',
            description: 'Min shared the customer meeting notes in Drive...',
            source: 'chat',
          },
          {
            label: '4h',
            value: 'Follow-up needed',
            description: 'Release notes draft still needs a short reply...',
            source: 'gmail',
          },
        ],
      },
      {
        id: 'meetings',
        kicker: 'Meetings',
        title: '2 meetings today',
        color: 'green',
        layout: 'meetings',
        rows: [
          {
            label: '15:00',
            value: 'Customer call',
            description: 'Google Meet',
            href: 'https://meet.google.com/',
            source: 'meet',
          },
          {
            label: '17:00',
            value: 'Project coordination',
            description: 'Meeting notes',
            href: 'https://docs.google.com/document/',
            source: 'docs',
          },
        ],
      },
    ],
    filters: [
      {
        id: 'projects',
        label: 'Projects',
        options: [
          { id: 'topsolid-cam', label: 'TopSolid CAM', color: 'teal', defaultChecked: true },
          { id: 'eureka-rollout', label: 'Eureka Rollout', color: 'blue', defaultChecked: true },
          { id: 'boxcon-support', label: 'Boxcon Support', color: 'purple' },
        ],
      },
      {
        id: 'status',
        label: 'Status',
        options: [
          { id: 'planned', label: 'Planned', color: 'purple' },
          { id: 'todo', label: 'Todo', color: 'orange', defaultChecked: true },
          { id: 'doing', label: 'Doing', color: 'blue', defaultChecked: true },
          { id: 'solved', label: 'Solved', color: 'green' },
        ],
      },
    ],
    calendar: {
      title: 'Workspace Calendar',
      subtitle: '',
      behavior: [
        'All instants are stored in UTC and displayed in each user’s configured time zone.',
        'Work, meetings, deadlines, and follow-ups can be shared read-only with users or groups.',
      ],
      itemTypes: [
        { id: 'work-period', label: 'Work period', color: 'blue', marker: 'line' },
        { id: 'follow-up', label: 'Follow-up', color: 'orange', marker: 'dot' },
        { id: 'customer-meeting', label: 'Customer meeting', color: 'teal', marker: 'meeting' },
        { id: 'deadline', label: 'Deadline', color: 'red', marker: 'milestone' },
        { id: 'solved', label: 'Solved issue', color: 'green', marker: 'due' },
      ],
    },
    board: {
      columns: [
        { id: 'todo', label: 'Todo', color: 'orange' },
        { id: 'doing', label: 'Doing', color: 'blue' },
        { id: 'waiting', label: 'Waiting', color: 'purple' },
        { id: 'solved', label: 'Solved', color: 'green' },
      ],
    },
    detailFields: [
      { id: 'type', label: 'Type' },
      { id: 'project', label: 'Project' },
      { id: 'customer', label: 'Customer' },
      { id: 'target', label: 'Target' },
    ],
    addItemFields: [
      {
        id: 'type',
        label: 'Type',
        type: 'select',
        options: ['Issue', 'Customer Request', 'Task', 'Meeting Action'],
        required: true,
      },
      { id: 'title', label: 'Title', type: 'text', fullWidth: true, required: true },
      { id: 'project', label: 'Project', type: 'text' },
      { id: 'category', label: 'Category', type: 'text' },
      { id: 'customer', label: 'Customer', type: 'text' },
      { id: 'assignee', label: 'Colleague or Assignee', type: 'text' },
      { id: 'startDate', label: 'Start Date', type: 'date' },
      { id: 'targetDate', label: 'Due Date', type: 'date' },
      { id: 'meetingLink', label: 'Meeting Link', type: 'url', fullWidth: true },
      {
        id: 'notes',
        label: 'Work Checklist and Notes',
        type: 'textarea',
        fullWidth: true,
        placeholder: 'Add work steps, customer context, decisions, and follow-up notes...',
      },
    ],
    timeline: {
      label: 'Work timeline',
      behavior: 'Projects, issues, customer requests, and scheduled work share one customer-focused timeline.',
    },
    integrations: [
      { provider: 'google_calendar', enabled: true, label: 'Google Calendar' },
      { provider: 'google_meet', enabled: false, label: 'Google Meet' },
      { provider: 'google_drive', enabled: false, label: 'Google Drive' },
      { provider: 'gmail', enabled: false, label: 'Gmail' },
      { provider: 'google_chat', enabled: false, label: 'Google Chat' },
      { provider: 'github', enabled: false, label: 'GitHub' },
    ],
  },
  {
    id: 'admin-console',
    displayName: 'Admin Console',
    icon: 'settings',
    enabled: true,
    purpose:
      'Manage users, workspace modes, integrations, permissions, audit logs, and system settings.',
    accent: { primary: '#8a5a00', secondary: '#4b5563' },
    features: ['board', 'timeline', 'checklist', 'notes', 'links', 'integrations'],
    views: ['board', 'agenda', 'timeline'],
    sidebar: [
      {
        id: 'menu',
        label: 'Menu',
        items: [
          { id: 'dashboard', label: 'Dashboard', icon: 'layout-dashboard' },
          { id: 'users', label: 'Users', icon: 'users' },
          { id: 'groups', label: 'Groups', icon: 'users' },
          { id: 'customers', label: 'Customers', icon: 'building-2' },
          { id: 'licenses', label: 'Licenses', icon: 'key-round' },
          { id: 'products', label: 'Products', icon: 'package' },
          { id: 'invoices', label: 'Invoices', icon: 'receipt-text' },
        ],
      },
      {
        id: 'settings',
        label: 'Setting',
        items: [
          { id: 'settings-general', label: 'General', icon: 'sliders-horizontal' },
          { id: 'permissions', label: 'Permissions', icon: 'circle-alert' },
          { id: 'audit-logs', label: 'Audit Logs', icon: 'list-checks' },
          { id: 'workspace-mode', label: 'Workspace Mode', icon: 'settings' },
        ],
      },
    ],
    dashboardCards: [
      {
        id: 'users',
        kicker: 'Users',
        title: 'Workspace access',
        pill: 'Admin',
        color: 'gray',
        rows: [
          { label: 'Active users', value: '12' },
          { label: 'Pending invites', value: '2' },
          { label: 'Admins', value: '3' },
        ],
      },
      {
        id: 'integrations',
        kicker: 'Integrations',
        title: 'Google connected',
        pill: 'OAuth',
        color: 'green',
        rows: [
          { label: 'Calendar', value: 'Ready' },
          { label: 'Drive', value: 'Ready' },
          { label: 'Gmail', value: 'Planned' },
        ],
      },
      {
        id: 'audit',
        kicker: 'Audit',
        title: '4 changes today',
        pill: 'Logs',
        color: 'orange',
        rows: [
          { label: 'Mode changes', value: '1' },
          { label: 'Permission changes', value: '2' },
          { label: 'Token refresh', value: '1' },
        ],
      },
    ],
    filters: [
      {
        id: 'admin-area',
        label: 'Admin Area',
        options: [
          { id: 'users', label: 'Users', color: 'blue', defaultChecked: true },
          { id: 'modes', label: 'Modes', color: 'purple', defaultChecked: true },
          { id: 'integrations', label: 'Integrations', color: 'green', defaultChecked: true },
        ],
      },
      {
        id: 'admin-status',
        label: 'Status',
        options: [
          { id: 'healthy', label: 'Healthy', color: 'green', defaultChecked: true },
          { id: 'review', label: 'Needs Review', color: 'orange', defaultChecked: true },
          { id: 'blocked', label: 'Blocked', color: 'red' },
        ],
      },
    ],
    calendar: {
      title: 'Admin Console',
      subtitle: 'Administration tasks, access reviews, integration checks, and audit milestones.',
      behavior: [
        'Admin events can track access reviews, integration setup, token renewal checks, and audit checkpoints.',
        'Mode settings remain configuration-driven so workspace modules can be enabled or hidden later.',
      ],
      itemTypes: [
        { id: 'access-review', label: 'Access review', color: 'blue', marker: 'milestone' },
        { id: 'integration-check', label: 'Integration check', color: 'green', marker: 'meeting' },
        { id: 'audit-log', label: 'Audit log', color: 'orange', marker: 'dot' },
      ],
    },
    board: {
      columns: [
        { id: 'review', label: 'Review', color: 'orange' },
        { id: 'configure', label: 'Configure', color: 'blue' },
        { id: 'monitor', label: 'Monitor', color: 'purple' },
        { id: 'done', label: 'Done', color: 'green' },
      ],
    },
    detailFields: [
      { id: 'type', label: 'Type' },
      { id: 'area', label: 'Area' },
      { id: 'owner', label: 'Owner' },
      { id: 'status', label: 'Status' },
    ],
    addItemFields: [
      {
        id: 'type',
        label: 'Type',
        type: 'select',
        options: ['User Task', 'Mode Setting', 'Integration', 'Permission Review', 'Audit Note'],
        required: true,
      },
      { id: 'title', label: 'Title', type: 'text', fullWidth: true, required: true },
      { id: 'area', label: 'Admin Area', type: 'text' },
      { id: 'owner', label: 'Owner', type: 'text' },
      { id: 'targetDate', label: 'Target Date', type: 'date' },
      {
        id: 'priority',
        label: 'Priority',
        type: 'priority',
        options: ['High', 'Medium', 'Low'],
      },
      { id: 'link', label: 'Reference Link', type: 'url', fullWidth: true },
      {
        id: 'notes',
        label: 'Admin Notes',
        type: 'textarea',
        fullWidth: true,
        placeholder: 'Add permission notes, integration steps, or audit context...',
      },
    ],
    timeline: {
      label: 'Admin timeline',
      behavior: 'Access reviews, mode rollout, and integration checks can render as administration tracks.',
    },
    integrations: [
      { provider: 'google_calendar', enabled: false, label: 'Google Calendar' },
      { provider: 'google_drive', enabled: false, label: 'Google Drive' },
      { provider: 'gmail', enabled: false, label: 'Gmail' },
      { provider: 'github', enabled: false, label: 'GitHub' },
      { provider: 'manual_url', enabled: true, label: 'Manual URLs' },
    ],
  },
  {
    id: 'support',
    displayName: 'Support CRM',
    icon: 'life-buoy',
    enabled: false,
    hidden: true,
    purpose:
      'Manage customers, support cases, Gmail threads, Google Meet links, Drive attachments, TopTrack ticket IDs, and future TopSolid PDM references.',
    accent: { primary: '#5f6f2f', secondary: '#0f766e' },
    features: ['calendar', 'agenda', 'board', 'timeline', 'customers', 'links', 'integrations'],
    views: ['month', 'agenda', 'board', 'timeline'],
    sidebar: [],
    dashboardCards: [],
    filters: [],
    calendar: {
      title: 'Support CRM Calendar',
      subtitle: 'Customer cases, HQ response status, and follow-up reminders.',
      itemTypes: [],
      behavior: ['Support cases can be modeled with shared calendar items and external links.'],
    },
    board: { columns: [] },
    detailFields: [],
    addItemFields: [],
    timeline: {
      label: 'Case timeline',
      behavior: 'Case status and follow-up windows can be tracked by shared calendar item fields.',
    },
    integrations: [
      { provider: 'gmail', enabled: false, label: 'Gmail' },
      { provider: 'google_meet', enabled: false, label: 'Google Meet' },
      { provider: 'google_drive', enabled: false, label: 'Google Drive' },
      { provider: 'toptrack', enabled: false, label: 'TopTrack' },
      { provider: 'topsolid_pdm', enabled: false, label: 'TopSolid PDM' },
    ],
  },
  {
    id: 'boxcon',
    displayName: 'Boxcon',
    icon: 'boxes',
    enabled: false,
    hidden: true,
    purpose:
      'Manage Boxcon development tasks, issues, customer requests, inventory and IoT todos, deployment notes, and meetings.',
    accent: { primary: '#a16207', secondary: '#705c37' },
    features: ['calendar', 'agenda', 'board', 'timeline', 'issues', 'customers', 'links'],
    views: ['month', 'agenda', 'board', 'timeline'],
    sidebar: [],
    dashboardCards: [],
    filters: [],
    calendar: {
      title: 'Boxcon Calendar',
      subtitle: 'Development, deployments, inventory workflows, device issues, and meetings.',
      itemTypes: [],
      behavior: ['Boxcon-specific work can extend the common issue and calendar models later.'],
    },
    board: { columns: [] },
    detailFields: [],
    addItemFields: [],
    timeline: {
      label: 'Boxcon timeline',
      behavior: 'Device, backend, mobile, kiosk, and deployment tasks can share timeline semantics.',
    },
    integrations: [
      { provider: 'google_meet', enabled: false, label: 'Google Meet' },
      { provider: 'google_drive', enabled: false, label: 'Google Drive' },
      { provider: 'github', enabled: false, label: 'GitHub' },
      { provider: 'manual_url', enabled: true, label: 'Manual URLs' },
    ],
  },
  {
    id: 'topsolid',
    displayName: 'TopSolid',
    icon: 'wrench',
    enabled: false,
    hidden: true,
    purpose:
      'Manage TopSolid reseller, support, product, HQ questions, TopTrack links, PDM references, customer cases, and Google Workspace communication.',
    accent: { primary: '#7c5c21', secondary: '#4f46e5' },
    features: ['calendar', 'agenda', 'board', 'timeline', 'customers', 'links', 'integrations'],
    views: ['month', 'agenda', 'board', 'timeline'],
    sidebar: [],
    dashboardCards: [],
    filters: [],
    calendar: {
      title: 'TopSolid Calendar',
      subtitle: 'Support sessions, reseller tasks, HQ questions, training, and follow-ups.',
      itemTypes: [],
      behavior: ['TopSolid support work can add specialized fields while reusing common links and cases.'],
    },
    board: { columns: [] },
    detailFields: [],
    addItemFields: [],
    timeline: {
      label: 'TopSolid timeline',
      behavior: 'HQ response windows, training requests, and license cases can render as timeline tracks.',
    },
    integrations: [
      { provider: 'gmail', enabled: false, label: 'Gmail' },
      { provider: 'google_meet', enabled: false, label: 'Google Meet' },
      { provider: 'google_drive', enabled: false, label: 'Google Drive' },
      { provider: 'toptrack', enabled: false, label: 'TopTrack' },
      { provider: 'topsolid_pdm', enabled: false, label: 'TopSolid PDM' },
    ],
  },
];
